"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import processing_service_v2_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class ConfigurationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ORCHESTRATOR_NAME_FIELD_NUMBER: builtins.int
    ORCHESTRATOR_VERSION_FIELD_NUMBER: builtins.int
    #* Human readable name of the orchestrator.
    orchestrator_name: typing.Text = ...
    #* Human readable version of the orchestrator.
    orchestrator_version: typing.Text = ...
    def __init__(self,
        *,
        orchestrator_name : typing.Text = ...,
        orchestrator_version : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"orchestrator_name",b"orchestrator_name",u"orchestrator_version",b"orchestrator_version"]) -> None: ...
global___ConfigurationRequest = ConfigurationRequest

class ConfigurationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    PROVIDER_NAME_FIELD_NUMBER: builtins.int
    PROVIDER_VERSION_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    PROVIDER_DESCRIPTION_FIELD_NUMBER: builtins.int
    #* Human readable name of the provider.
    provider_name: typing.Text = ...
    #* Human readable version of the provider.
    provider_version: typing.Text = ...
    #* Indicates which protocol to use to communicate to this provider.
    @property
    def version(self) -> global___ProtocolVersion: ...
    #* Extra description information for a processor that is logically separate from the version information.
    provider_description: typing.Text = ...
    def __init__(self,
        *,
        provider_name : typing.Text = ...,
        provider_version : typing.Text = ...,
        version : typing.Optional[global___ProtocolVersion] = ...,
        provider_description : typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"version",b"version"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"provider_description",b"provider_description",u"provider_name",b"provider_name",u"provider_version",b"provider_version",u"version",b"version"]) -> None: ...
global___ConfigurationResponse = ConfigurationResponse

class ProtocolVersion(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    V2_FIELD_NUMBER: builtins.int
    # Implements ProcessingService from ./processing-service-v2.proto.
    @property
    def v2(self) -> processing_service_v2_pb2.ProcessorV2Config: ...
    def __init__(self,
        *,
        v2 : typing.Optional[processing_service_v2_pb2.ProcessorV2Config] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"config",b"config",u"v2",b"v2"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"config",b"config",u"v2",b"v2"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal[u"config",b"config"]) -> typing.Optional[typing_extensions.Literal["v2"]]: ...
global___ProtocolVersion = ProtocolVersion
