# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: configuration-service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import processing_service_v2_pb2 as processing__service__v2__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='configuration-service.proto',
  package='aip.configuration.v1',
  syntax='proto3',
  serialized_options=b'\n$com.palantir.aip.proto.configurationB\014ConfigProtos',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1b\x63onfiguration-service.proto\x12\x14\x61ip.configuration.v1\x1a\x1bprocessing-service-v2.proto\"O\n\x14\x43onfigurationRequest\x12\x19\n\x11orchestrator_name\x18\x01 \x01(\t\x12\x1c\n\x14orchestrator_version\x18\x02 \x01(\t\"\x9e\x01\n\x15\x43onfigurationResponse\x12\x15\n\rprovider_name\x18\x01 \x01(\t\x12\x18\n\x10provider_version\x18\x02 \x01(\t\x12\x36\n\x07version\x18\x04 \x01(\x0b\x32%.aip.configuration.v1.ProtocolVersion\x12\x1c\n\x14provider_description\x18\x05 \x01(\t\"N\n\x0fProtocolVersion\x12\x31\n\x02v2\x18\x02 \x01(\x0b\x32#.aip.processor.v2.ProcessorV2ConfigH\x00\x42\x08\n\x06\x63onfig2~\n\x14\x43onfigurationService\x12\x66\n\tConfigure\x12*.aip.configuration.v1.ConfigurationRequest\x1a+.aip.configuration.v1.ConfigurationResponse\"\x00\x42\x34\n$com.palantir.aip.proto.configurationB\x0c\x43onfigProtosb\x06proto3'
  ,
  dependencies=[processing__service__v2__pb2.DESCRIPTOR,])




_CONFIGURATIONREQUEST = _descriptor.Descriptor(
  name='ConfigurationRequest',
  full_name='aip.configuration.v1.ConfigurationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='orchestrator_name', full_name='aip.configuration.v1.ConfigurationRequest.orchestrator_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='orchestrator_version', full_name='aip.configuration.v1.ConfigurationRequest.orchestrator_version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=161,
)


_CONFIGURATIONRESPONSE = _descriptor.Descriptor(
  name='ConfigurationResponse',
  full_name='aip.configuration.v1.ConfigurationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='provider_name', full_name='aip.configuration.v1.ConfigurationResponse.provider_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='provider_version', full_name='aip.configuration.v1.ConfigurationResponse.provider_version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='aip.configuration.v1.ConfigurationResponse.version', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='provider_description', full_name='aip.configuration.v1.ConfigurationResponse.provider_description', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=322,
)


_PROTOCOLVERSION = _descriptor.Descriptor(
  name='ProtocolVersion',
  full_name='aip.configuration.v1.ProtocolVersion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='v2', full_name='aip.configuration.v1.ProtocolVersion.v2', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='config', full_name='aip.configuration.v1.ProtocolVersion.config',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=324,
  serialized_end=402,
)

_CONFIGURATIONRESPONSE.fields_by_name['version'].message_type = _PROTOCOLVERSION
_PROTOCOLVERSION.fields_by_name['v2'].message_type = processing__service__v2__pb2._PROCESSORV2CONFIG
_PROTOCOLVERSION.oneofs_by_name['config'].fields.append(
  _PROTOCOLVERSION.fields_by_name['v2'])
_PROTOCOLVERSION.fields_by_name['v2'].containing_oneof = _PROTOCOLVERSION.oneofs_by_name['config']
DESCRIPTOR.message_types_by_name['ConfigurationRequest'] = _CONFIGURATIONREQUEST
DESCRIPTOR.message_types_by_name['ConfigurationResponse'] = _CONFIGURATIONRESPONSE
DESCRIPTOR.message_types_by_name['ProtocolVersion'] = _PROTOCOLVERSION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConfigurationRequest = _reflection.GeneratedProtocolMessageType('ConfigurationRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGURATIONREQUEST,
  '__module__' : 'configuration_service_pb2'
  # @@protoc_insertion_point(class_scope:aip.configuration.v1.ConfigurationRequest)
  })
_sym_db.RegisterMessage(ConfigurationRequest)

ConfigurationResponse = _reflection.GeneratedProtocolMessageType('ConfigurationResponse', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGURATIONRESPONSE,
  '__module__' : 'configuration_service_pb2'
  # @@protoc_insertion_point(class_scope:aip.configuration.v1.ConfigurationResponse)
  })
_sym_db.RegisterMessage(ConfigurationResponse)

ProtocolVersion = _reflection.GeneratedProtocolMessageType('ProtocolVersion', (_message.Message,), {
  'DESCRIPTOR' : _PROTOCOLVERSION,
  '__module__' : 'configuration_service_pb2'
  # @@protoc_insertion_point(class_scope:aip.configuration.v1.ProtocolVersion)
  })
_sym_db.RegisterMessage(ProtocolVersion)


DESCRIPTOR._options = None

_CONFIGURATIONSERVICE = _descriptor.ServiceDescriptor(
  name='ConfigurationService',
  full_name='aip.configuration.v1.ConfigurationService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=404,
  serialized_end=530,
  methods=[
  _descriptor.MethodDescriptor(
    name='Configure',
    full_name='aip.configuration.v1.ConfigurationService.Configure',
    index=0,
    containing_service=None,
    input_type=_CONFIGURATIONREQUEST,
    output_type=_CONFIGURATIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONFIGURATIONSERVICE)

DESCRIPTOR.services_by_name['ConfigurationService'] = _CONFIGURATIONSERVICE

# @@protoc_insertion_point(module_scope)
