# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import configuration_service_pb2 as configuration__service__pb2


class ConfigurationServiceStub(object):
    """*
    All processors must implement Configuration Service, no messages will be sent to other RPC endpoints until
    configuration response is received.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Configure = channel.unary_unary(
                '/aip.configuration.v1.ConfigurationService/Configure',
                request_serializer=configuration__service__pb2.ConfigurationRequest.SerializeToString,
                response_deserializer=configuration__service__pb2.ConfigurationResponse.FromString,
                )


class ConfigurationServiceServicer(object):
    """*
    All processors must implement Configuration Service, no messages will be sent to other RPC endpoints until
    configuration response is received.
    """

    def Configure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConfigurationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Configure': grpc.unary_unary_rpc_method_handler(
                    servicer.Configure,
                    request_deserializer=configuration__service__pb2.ConfigurationRequest.FromString,
                    response_serializer=configuration__service__pb2.ConfigurationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aip.configuration.v1.ConfigurationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ConfigurationService(object):
    """*
    All processors must implement Configuration Service, no messages will be sent to other RPC endpoints until
    configuration response is received.
    """

    @staticmethod
    def Configure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aip.configuration.v1.ConfigurationService/Configure',
            configuration__service__pb2.ConfigurationRequest.SerializeToString,
            configuration__service__pb2.ConfigurationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
