"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.duration_pb2
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class ImageFormat(_ImageFormat, metaclass=_ImageFormatEnumTypeWrapper):
    pass
class _ImageFormat:
    V = typing.NewType('V', builtins.int)
class _ImageFormatEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ImageFormat.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    RGB888 = ImageFormat.V(0)
    PNG = ImageFormat.V(1)
    TIFF = ImageFormat.V(2)
    BGR888 = ImageFormat.V(3)
    NITF21 = ImageFormat.V(4)

RGB888 = ImageFormat.V(0)
PNG = ImageFormat.V(1)
TIFF = ImageFormat.V(2)
BGR888 = ImageFormat.V(3)
NITF21 = ImageFormat.V(4)
global___ImageFormat = ImageFormat


class ProcessorV2Config(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class Capability(_Capability, metaclass=_CapabilityEnumTypeWrapper):
        pass
    class _Capability:
        V = typing.NewType('V', builtins.int)
    class _CapabilityEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Capability.V], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        GEO_REGISTER = ProcessorV2Config.Capability.V(0)
        INFER = ProcessorV2Config.Capability.V(1)
        TRACK = ProcessorV2Config.Capability.V(2)

    GEO_REGISTER = ProcessorV2Config.Capability.V(0)
    INFER = ProcessorV2Config.Capability.V(1)
    TRACK = ProcessorV2Config.Capability.V(2)

    IMAGE_FORMAT_FIELD_NUMBER: builtins.int
    CAPABILITIES_FIELD_NUMBER: builtins.int
    #* Indicates to the orchestrator in what format to emit frames to this provider.
    image_format: global___ImageFormat.V = ...
    #* A non-empty list of capabilities this ProcessingService supports.
    @property
    def capabilities(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___ProcessorV2Config.Capability.V]: ...
    def __init__(self,
        *,
        image_format : global___ImageFormat.V = ...,
        capabilities : typing.Optional[typing.Iterable[global___ProcessorV2Config.Capability.V]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"capabilities",b"capabilities",u"image_format",b"image_format"]) -> None: ...
global___ProcessorV2Config = ProcessorV2Config

class RequestHeader(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    IDENTIFIER_FIELD_NUMBER: builtins.int
    DEADLINE_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    @property
    def identifier(self) -> global___Identifier: ...
    @property
    def deadline(self) -> google.protobuf.duration_pb2.Duration: ...
    @property
    def timestamp(self) -> global___Timestamp: ...
    def __init__(self,
        *,
        identifier : typing.Optional[global___Identifier] = ...,
        deadline : typing.Optional[google.protobuf.duration_pb2.Duration] = ...,
        timestamp : typing.Optional[global___Timestamp] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"deadline",b"deadline",u"identifier",b"identifier",u"timestamp",b"timestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"deadline",b"deadline",u"identifier",b"identifier",u"timestamp",b"timestamp"]) -> None: ...
global___RequestHeader = RequestHeader

#* The unique identifier for a unit of work and its associated result.
class Identifier(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    STREAM_ID_FIELD_NUMBER: builtins.int
    FRAME_ID_FIELD_NUMBER: builtins.int
    stream_id: builtins.int = ...
    frame_id: builtins.int = ...
    def __init__(self,
        *,
        stream_id : builtins.int = ...,
        frame_id : builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"frame_id",b"frame_id",u"stream_id",b"stream_id"]) -> None: ...
global___Identifier = Identifier

class Timestamp(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NANOS_FIELD_NUMBER: builtins.int
    #*
    # Elapsed nanoseconds from some unspecified point in time. Guaranteed to be monotonically increasing across
    # subsequent frames on the same stream.
    nanos: builtins.int = ...
    def __init__(self,
        *,
        nanos : builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"nanos",b"nanos"]) -> None: ...
global___Timestamp = Timestamp

class GeoRegistrationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    HEADER_FIELD_NUMBER: builtins.int
    FRAME_FIELD_NUMBER: builtins.int
    @property
    def header(self) -> global___RequestHeader: ...
    @property
    def frame(self) -> global___Frame: ...
    def __init__(self,
        *,
        header : typing.Optional[global___RequestHeader] = ...,
        frame : typing.Optional[global___Frame] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"frame",b"frame",u"header",b"header"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"frame",b"frame",u"header",b"header"]) -> None: ...
global___GeoRegistrationRequest = GeoRegistrationRequest

class GeoRegistrationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    IDENTIFIER_FIELD_NUMBER: builtins.int
    GEO_REGISTRATION_FIELD_NUMBER: builtins.int
    @property
    def identifier(self) -> global___Identifier: ...
    @property
    def geo_registration(self) -> global___GeoRegistration: ...
    def __init__(self,
        *,
        identifier : typing.Optional[global___Identifier] = ...,
        geo_registration : typing.Optional[global___GeoRegistration] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"geo_registration",b"geo_registration",u"identifier",b"identifier"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"geo_registration",b"geo_registration",u"identifier",b"identifier"]) -> None: ...
global___GeoRegistrationResponse = GeoRegistrationResponse

class InferenceRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    HEADER_FIELD_NUMBER: builtins.int
    FRAME_FIELD_NUMBER: builtins.int
    @property
    def header(self) -> global___RequestHeader: ...
    @property
    def frame(self) -> global___Frame: ...
    def __init__(self,
        *,
        header : typing.Optional[global___RequestHeader] = ...,
        frame : typing.Optional[global___Frame] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"frame",b"frame",u"header",b"header"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"frame",b"frame",u"header",b"header"]) -> None: ...
global___InferenceRequest = InferenceRequest

class InferenceResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    IDENTIFIER_FIELD_NUMBER: builtins.int
    INFERENCES_FIELD_NUMBER: builtins.int
    @property
    def identifier(self) -> global___Identifier: ...
    @property
    def inferences(self) -> global___Inferences: ...
    def __init__(self,
        *,
        identifier : typing.Optional[global___Identifier] = ...,
        inferences : typing.Optional[global___Inferences] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"identifier",b"identifier",u"inferences",b"inferences"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"identifier",b"identifier",u"inferences",b"inferences"]) -> None: ...
global___InferenceResponse = InferenceResponse

class TrackRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    HEADER_FIELD_NUMBER: builtins.int
    FRAME_FIELD_NUMBER: builtins.int
    INFERENCES_FIELD_NUMBER: builtins.int
    GEO_REGISTRATION_FIELD_NUMBER: builtins.int
    @property
    def header(self) -> global___RequestHeader: ...
    @property
    def frame(self) -> global___Frame: ...
    @property
    def inferences(self) -> global___Inferences: ...
    @property
    def geo_registration(self) -> global___GeoRegistration: ...
    def __init__(self,
        *,
        header : typing.Optional[global___RequestHeader] = ...,
        frame : typing.Optional[global___Frame] = ...,
        inferences : typing.Optional[global___Inferences] = ...,
        geo_registration : typing.Optional[global___GeoRegistration] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"frame",b"frame",u"geo_registration",b"geo_registration",u"header",b"header",u"inferences",b"inferences",u"maybe_geo_registration",b"maybe_geo_registration",u"maybe_inferences",b"maybe_inferences"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"frame",b"frame",u"geo_registration",b"geo_registration",u"header",b"header",u"inferences",b"inferences",u"maybe_geo_registration",b"maybe_geo_registration",u"maybe_inferences",b"maybe_inferences"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal[u"maybe_geo_registration",b"maybe_geo_registration"]) -> typing.Optional[typing_extensions.Literal["geo_registration"]]: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal[u"maybe_inferences",b"maybe_inferences"]) -> typing.Optional[typing_extensions.Literal["inferences"]]: ...
global___TrackRequest = TrackRequest

class GeoRegistration(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    LATTICE_FIELD_NUMBER: builtins.int
    CONFIDENCE_FIELD_NUMBER: builtins.int
    UPDATEDMETADATA_FIELD_NUMBER: builtins.int
    @property
    def lattice(self) -> global___Lattice: ...
    confidence: builtins.float = ...
    @property
    def updatedMetadata(self) -> global___UasMetadata: ...
    def __init__(self,
        *,
        lattice : typing.Optional[global___Lattice] = ...,
        confidence : builtins.float = ...,
        updatedMetadata : typing.Optional[global___UasMetadata] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"lattice",b"lattice",u"updatedMetadata",b"updatedMetadata"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"confidence",b"confidence",u"lattice",b"lattice",u"updatedMetadata",b"updatedMetadata"]) -> None: ...
global___GeoRegistration = GeoRegistration

class Inferences(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    INFERENCE_FIELD_NUMBER: builtins.int
    @property
    def inference(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Inference]: ...
    def __init__(self,
        *,
        inference : typing.Optional[typing.Iterable[global___Inference]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"inference",b"inference"]) -> None: ...
global___Inferences = Inferences

class Inference(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    INFERENCEID_FIELD_NUMBER: builtins.int
    BOX_FIELD_NUMBER: builtins.int
    POLYGON_FIELD_NUMBER: builtins.int
    VELOCITY_FIELD_NUMBER: builtins.int
    #* Persistent id of a particular inference that's used to tie together inferences across frames.
    inferenceId: typing.Text = ...
    @property
    def box(self) -> global___BoundingBox: ...
    @property
    def polygon(self) -> global___BoundingPolygon: ...
    @property
    def velocity(self) -> global___Velocity: ...
    def __init__(self,
        *,
        inferenceId : typing.Text = ...,
        box : typing.Optional[global___BoundingBox] = ...,
        polygon : typing.Optional[global___BoundingPolygon] = ...,
        velocity : typing.Optional[global___Velocity] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"box",b"box",u"inference",b"inference",u"polygon",b"polygon",u"velocity",b"velocity"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"box",b"box",u"inference",b"inference",u"inferenceId",b"inferenceId",u"polygon",b"polygon",u"velocity",b"velocity"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal[u"inference",b"inference"]) -> typing.Optional[typing_extensions.Literal["box","polygon"]]: ...
global___Inference = Inference

#
# GeoCoordinate represents a unique point on the Earth's surface, defined by a latitude and longitude.
class GeoCoordinate(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    LATITUDE_FIELD_NUMBER: builtins.int
    LONGITUDE_FIELD_NUMBER: builtins.int
    latitude: builtins.float = ...
    longitude: builtins.float = ...
    def __init__(self,
        *,
        latitude : builtins.float = ...,
        longitude : builtins.float = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"latitude",b"latitude",u"longitude",b"longitude"]) -> None: ...
global___GeoCoordinate = GeoCoordinate

#
# A rectangular container defined by its coordinates:
#   drawn from (c0.row, c0.col) to (c1.row, c1.col)
#   height = c1.row - c0.row
#   width = c1.col - c0.col
class BoundingBox(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    C0_FIELD_NUMBER: builtins.int
    C1_FIELD_NUMBER: builtins.int
    CLASSIFICATIONS_FIELD_NUMBER: builtins.int
    #* Upper left corner
    @property
    def c0(self) -> global___UnitCoordinate: ...
    #* Lower right corner
    @property
    def c1(self) -> global___UnitCoordinate: ...
    #*
    # Each BoundingBox may be labeled with potentially many classifications. Classifications do not necessarily need
    # to relate, and it’s valid, for instance, to return results such as:
    #   [ motorcycle: 0.5, person: 0.5]
    #   [ vehicle: 0.9, car: 0.5, truck: 0.4 ]
    @property
    def classifications(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Classification]: ...
    def __init__(self,
        *,
        c0 : typing.Optional[global___UnitCoordinate] = ...,
        c1 : typing.Optional[global___UnitCoordinate] = ...,
        classifications : typing.Optional[typing.Iterable[global___Classification]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"c0",b"c0",u"c1",b"c1"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"c0",b"c0",u"c1",b"c1",u"classifications",b"classifications"]) -> None: ...
global___BoundingBox = BoundingBox

class BoundingPolygon(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    POLYGON_FIELD_NUMBER: builtins.int
    CLASSIFICATIONS_FIELD_NUMBER: builtins.int
    @property
    def polygon(self) -> global___Polygon: ...
    @property
    def classifications(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Classification]: ...
    def __init__(self,
        *,
        polygon : typing.Optional[global___Polygon] = ...,
        classifications : typing.Optional[typing.Iterable[global___Classification]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"polygon",b"polygon"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"classifications",b"classifications",u"polygon",b"polygon"]) -> None: ...
global___BoundingPolygon = BoundingPolygon

#* A closed polygon defined by the provided vertices (last vertex is connected to the first).
class Polygon(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    VERTICES_FIELD_NUMBER: builtins.int
    @property
    def vertices(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___UnitCoordinate]: ...
    def __init__(self,
        *,
        vertices : typing.Optional[typing.Iterable[global___UnitCoordinate]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"vertices",b"vertices"]) -> None: ...
global___Polygon = Polygon

#* A closed polygon defined by the provided geo vertices (last vertex is connected to the first).
class GeoPolygon(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    VERTICES_FIELD_NUMBER: builtins.int
    @property
    def vertices(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___GeoCoordinate]: ...
    def __init__(self,
        *,
        vertices : typing.Optional[typing.Iterable[global___GeoCoordinate]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"vertices",b"vertices"]) -> None: ...
global___GeoPolygon = GeoPolygon

#*
# Specifies a location where row and col are specified in unit space [0,1].
# Corners have the following UnitCoordinates:
#
# Upper-Left   row: 0  col: 0
# Upper-Right  row: 0  col: 1
# Lower-Left   row: 1  col: 0
# Lower-Right  row: 1  col: 1
class UnitCoordinate(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ROW_FIELD_NUMBER: builtins.int
    COL_FIELD_NUMBER: builtins.int
    row: builtins.float = ...
    col: builtins.float = ...
    def __init__(self,
        *,
        row : builtins.float = ...,
        col : builtins.float = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"col",b"col",u"row",b"row"]) -> None: ...
global___UnitCoordinate = UnitCoordinate

class Classification(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TYPE_FIELD_NUMBER: builtins.int
    CONFIDENCE_FIELD_NUMBER: builtins.int
    #* A pre-agreed identifier that the orchestration system is agnostic to.
    type: typing.Text = ...
    #* Value in the range [0,1] representing how likely the referenced object is the given type.
    confidence: builtins.float = ...
    def __init__(self,
        *,
        type : typing.Text = ...,
        confidence : builtins.float = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"confidence",b"confidence",u"type",b"type"]) -> None: ...
global___Classification = Classification

#* Square lattice of points representing the intersection of the sensor with the Earth.
class Lattice(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class Point(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        COORDINATE_FIELD_NUMBER: builtins.int
        LATITUDE_FIELD_NUMBER: builtins.int
        LONGITUDE_FIELD_NUMBER: builtins.int
        ELEVATION_FIELD_NUMBER: builtins.int
        #* Coordinate in the image that corresponds to the given lat, long, and elevation.
        @property
        def coordinate(self) -> global___UnitCoordinate: ...
        #* Degrees. Latitude.
        latitude: builtins.float = ...
        #* Degrees. Longitude.
        longitude: builtins.float = ...
        #* Meters. Elevation.
        elevation: builtins.float = ...
        def __init__(self,
            *,
            coordinate : typing.Optional[global___UnitCoordinate] = ...,
            latitude : builtins.float = ...,
            longitude : builtins.float = ...,
            elevation : builtins.float = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal[u"coordinate",b"coordinate"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"coordinate",b"coordinate",u"elevation",b"elevation",u"latitude",b"latitude",u"longitude",b"longitude"]) -> None: ...

    EARTH_INTERSECTION_FIELD_NUMBER: builtins.int
    @property
    def earth_intersection(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Lattice.Point]: ...
    def __init__(self,
        *,
        earth_intersection : typing.Optional[typing.Iterable[global___Lattice.Point]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"earth_intersection",b"earth_intersection"]) -> None: ...
global___Lattice = Lattice

class Velocity(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    PIXEL_FIELD_NUMBER: builtins.int
    # spatial-velocity support to be added later
    @property
    def pixel(self) -> global___PixelVelocityVector: ...
    def __init__(self,
        *,
        pixel : typing.Optional[global___PixelVelocityVector] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"pixel",b"pixel",u"velocity",b"velocity"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"pixel",b"pixel",u"velocity",b"velocity"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal[u"velocity",b"velocity"]) -> typing.Optional[typing_extensions.Literal["pixel"]]: ...
global___Velocity = Velocity

class PixelVelocityVector(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    X_FIELD_NUMBER: builtins.int
    Y_FIELD_NUMBER: builtins.int
    #* Indicates row-motion in unit pixel-space. Positive values indicate motion to image-right.
    x: builtins.float = ...
    #* Indicates columnar-motion in unit pixel-space. Positive values indicate motion to image-down.
    y: builtins.float = ...
    def __init__(self,
        *,
        x : builtins.float = ...,
        y : builtins.float = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"x",b"x",u"y",b"y"]) -> None: ...
global___PixelVelocityVector = PixelVelocityVector

class Frame(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    IMAGE_FIELD_NUMBER: builtins.int
    UAS_METADATA_FIELD_NUMBER: builtins.int
    @property
    def image(self) -> global___Image: ...
    @property
    def uas_metadata(self) -> global___UasMetadata: ...
    def __init__(self,
        *,
        image : typing.Optional[global___Image] = ...,
        uas_metadata : typing.Optional[global___UasMetadata] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"image",b"image",u"uas_metadata",b"uas_metadata"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"image",b"image",u"uas_metadata",b"uas_metadata"]) -> None: ...
global___Frame = Frame

class Image(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    RGB_IMAGE_FIELD_NUMBER: builtins.int
    PNG_IMAGE_FIELD_NUMBER: builtins.int
    TIFF_IMAGE_FIELD_NUMBER: builtins.int
    BGR_IMAGE_FIELD_NUMBER: builtins.int
    NITF21_IMAGE_FIELD_NUMBER: builtins.int
    @property
    def rgb_image(self) -> global___Rgb888Image: ...
    @property
    def png_image(self) -> global___PngImage: ...
    @property
    def tiff_image(self) -> global___TiffImage: ...
    @property
    def bgr_image(self) -> global___Bgr888Image: ...
    @property
    def nitf21_image(self) -> global___Nitf21Image: ...
    def __init__(self,
        *,
        rgb_image : typing.Optional[global___Rgb888Image] = ...,
        png_image : typing.Optional[global___PngImage] = ...,
        tiff_image : typing.Optional[global___TiffImage] = ...,
        bgr_image : typing.Optional[global___Bgr888Image] = ...,
        nitf21_image : typing.Optional[global___Nitf21Image] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"bgr_image",b"bgr_image",u"image",b"image",u"nitf21_image",b"nitf21_image",u"png_image",b"png_image",u"rgb_image",b"rgb_image",u"tiff_image",b"tiff_image"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"bgr_image",b"bgr_image",u"image",b"image",u"nitf21_image",b"nitf21_image",u"png_image",b"png_image",u"rgb_image",b"rgb_image",u"tiff_image",b"tiff_image"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal[u"image",b"image"]) -> typing.Optional[typing_extensions.Literal["rgb_image","png_image","tiff_image","bgr_image","nitf21_image"]]: ...
global___Image = Image

class Rgb888Image(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    WIDTH_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    #* Width of the image in pixels.
    width: builtins.int = ...
    #* Height of the image in pixels.
    height: builtins.int = ...
    #*
    # The path to an RGB888 image arranged in hwc (height-width-channel) order.
    #
    # In order to get the pixel value at row 'r' and column 'c', you would index into the file as follows:
    #
    # ```
    # int rowOffset    = r * width * 3
    # int columnOffset = c * 3
    # int pixelIndex   = rowOffset + columnOffset
    # byte red   = bytes[pixelIndex]
    # byte green = bytes[pixelIndex + 1]
    # byte blue  = bytes[pixelIndex + 2]
    # ```
    path: typing.Text = ...
    def __init__(self,
        *,
        width : builtins.int = ...,
        height : builtins.int = ...,
        path : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"height",b"height",u"path",b"path",u"width",b"width"]) -> None: ...
global___Rgb888Image = Rgb888Image

class Bgr888Image(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    WIDTH_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    width: builtins.int = ...
    height: builtins.int = ...
    #* The path to a BGR888 image arranged in hwc (height-width-channel) order.
    path: typing.Text = ...
    def __init__(self,
        *,
        width : builtins.int = ...,
        height : builtins.int = ...,
        path : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"height",b"height",u"path",b"path",u"width",b"width"]) -> None: ...
global___Bgr888Image = Bgr888Image

class PngImage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    WIDTH_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    width: builtins.int = ...
    height: builtins.int = ...
    #* The path to a PNG encoded image.
    path: typing.Text = ...
    def __init__(self,
        *,
        width : builtins.int = ...,
        height : builtins.int = ...,
        path : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"height",b"height",u"path",b"path",u"width",b"width"]) -> None: ...
global___PngImage = PngImage

class TiffImage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    WIDTH_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    width: builtins.int = ...
    height: builtins.int = ...
    #* The path to a TIFF encoded image.
    path: typing.Text = ...
    def __init__(self,
        *,
        width : builtins.int = ...,
        height : builtins.int = ...,
        path : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"height",b"height",u"path",b"path",u"width",b"width"]) -> None: ...
global___TiffImage = TiffImage

class Nitf21Image(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    PATH_FIELD_NUMBER: builtins.int
    #* Path to a NITF 2.1 spec image
    path: typing.Text = ...
    def __init__(self,
        *,
        path : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"path",b"path"]) -> None: ...
global___Nitf21Image = Nitf21Image

class DigitalGlobeMetadata(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    FEATURE_ID_FIELD_NUMBER: builtins.int
    SOURCE_FIELD_NUMBER: builtins.int
    NIIRS_FIELD_NUMBER: builtins.int
    PRODUCT_TYPE_FIELD_NUMBER: builtins.int
    OFF_NADIR_DEGREES_FIELD_NUMBER: builtins.int
    SUN_ELEVATION_DEGREES_FIELD_NUMBER: builtins.int
    SUN_AZIMUTH_DEGREES_FIELD_NUMBER: builtins.int
    GROUND_SAMPLE_DISTANCE_CENTIMETERS_FIELD_NUMBER: builtins.int
    TOP_LEFT_FIELD_NUMBER: builtins.int
    TOP_RIGHT_FIELD_NUMBER: builtins.int
    BOTTOM_RIGHT_FIELD_NUMBER: builtins.int
    BOTTOM_LEFT_FIELD_NUMBER: builtins.int
    #* DigitalGlobe feature identifier
    feature_id: typing.Text = ...
    #* Source satellite & band: e.g. WV03_VNIR (corresponding to WorldView-3 Visible/Near-Infrared)
    source: typing.Text = ...
    #* National Image Interpretability Rating Scale score.
    niirs: builtins.int = ...
    #* DigitalGlobe product type
    product_type: typing.Text = ...
    #* Degrees within range [0, 90]. Off-nadir angle. Angle measured from nadir to frame center.
    off_nadir_degrees: builtins.float = ...
    #* Degrees within range [-90, 90]. Angle of sun above horizon. Negative elevation angle indicates nightime image.
    sun_elevation_degrees: builtins.float = ...
    #* Degrees within range [0, 360]. Sun azimuth.
    sun_azimuth_degrees: builtins.float = ...
    #* Scale factor mapping pixel-space to world space, as measured at the center of the frame.
    ground_sample_distance_centimeters: builtins.int = ...
    #* Corner points, in world coordinates
    @property
    def top_left(self) -> global___GeoCoordinate: ...
    @property
    def top_right(self) -> global___GeoCoordinate: ...
    @property
    def bottom_right(self) -> global___GeoCoordinate: ...
    @property
    def bottom_left(self) -> global___GeoCoordinate: ...
    def __init__(self,
        *,
        feature_id : typing.Text = ...,
        source : typing.Text = ...,
        niirs : builtins.int = ...,
        product_type : typing.Text = ...,
        off_nadir_degrees : builtins.float = ...,
        sun_elevation_degrees : builtins.float = ...,
        sun_azimuth_degrees : builtins.float = ...,
        ground_sample_distance_centimeters : builtins.int = ...,
        top_left : typing.Optional[global___GeoCoordinate] = ...,
        top_right : typing.Optional[global___GeoCoordinate] = ...,
        bottom_right : typing.Optional[global___GeoCoordinate] = ...,
        bottom_left : typing.Optional[global___GeoCoordinate] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"bottom_left",b"bottom_left",u"bottom_right",b"bottom_right",u"top_left",b"top_left",u"top_right",b"top_right"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"bottom_left",b"bottom_left",u"bottom_right",b"bottom_right",u"feature_id",b"feature_id",u"ground_sample_distance_centimeters",b"ground_sample_distance_centimeters",u"niirs",b"niirs",u"off_nadir_degrees",b"off_nadir_degrees",u"product_type",b"product_type",u"source",b"source",u"sun_azimuth_degrees",b"sun_azimuth_degrees",u"sun_elevation_degrees",b"sun_elevation_degrees",u"top_left",b"top_left",u"top_right",b"top_right"]) -> None: ...
global___DigitalGlobeMetadata = DigitalGlobeMetadata

class ProviderMetadata(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    DIGITAL_GLOBE_FIELD_NUMBER: builtins.int
    @property
    def digital_globe(self) -> global___DigitalGlobeMetadata: ...
    def __init__(self,
        *,
        digital_globe : typing.Optional[global___DigitalGlobeMetadata] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"digital_globe",b"digital_globe",u"metadata",b"metadata"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"digital_globe",b"digital_globe",u"metadata",b"metadata"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal[u"metadata",b"metadata"]) -> typing.Optional[typing_extensions.Literal["digital_globe"]]: ...
global___ProviderMetadata = ProviderMetadata

#* Subset of the tags from 0601.4, with tag number == protobuf field number.
class UasMetadata(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    PLATFORM_HEADING_ANGLE_FIELD_NUMBER: builtins.int
    PLATFORM_PITCH_ANGLE_FIELD_NUMBER: builtins.int
    PLATFORM_ROLL_ANGLE_FIELD_NUMBER: builtins.int
    SENSOR_LATITUDE_FIELD_NUMBER: builtins.int
    SENSOR_LONGITUDE_FIELD_NUMBER: builtins.int
    SENSOR_TRUE_ALTITUDE_FIELD_NUMBER: builtins.int
    SENSOR_HORIZONTAL_FOV_FIELD_NUMBER: builtins.int
    SENSOR_VERTICAL_FOV_FIELD_NUMBER: builtins.int
    SENSOR_RELATIVE_AZIMUTH_ANGLE_FIELD_NUMBER: builtins.int
    SENSOR_RELATIVE_ELEVATION_ANGLE_FIELD_NUMBER: builtins.int
    SENSOR_RELATIVE_ROLL_ANGLE_FIELD_NUMBER: builtins.int
    IMAGE_SOURCE_SENSOR_FIELD_NUMBER: builtins.int
    PROVIDER_METADATA_FIELD_NUMBER: builtins.int
    #* Degrees within range [0, 360]. Aircraft heading angle. Relative between longitudinal axis and True North measured in the horizontal plane.
    platform_heading_angle: builtins.float = ...
    #* Degrees within range [-20, 20]. Aircraft pitch angle. Angle between longitudinal axis and horzontal plane. Positive angles above horizontal plane.
    platform_pitch_angle: builtins.float = ...
    #* Degrees within range [-50, 50]. Platform roll angle. Angle between transverse axis and horizontal plane. Positive angles for right wing lowered below horizontal plane.
    platform_roll_angle: builtins.float = ...
    #* Degrees within range [-90, 90]. Sensor Latitude. Based on WGS84 ellipsoid.
    sensor_latitude: builtins.float = ...
    #* Degrees within range [-180, 180]. Sensor Longitude. Based on WGS84 ellipsoid.
    sensor_longitude: builtins.float = ...
    #* Meters within range [-900, 19000]. Altitude of sensor as measured from Mean Sea Level (MSL).
    sensor_true_altitude: builtins.float = ...
    #* Degrees within range [0, 180]. Horizontal field of view of selected imaging sensor.
    sensor_horizontal_fov: builtins.float = ...
    #* Degrees within range [0, 180]. Vertical field of view of selected imaging sensor.
    sensor_vertical_fov: builtins.float = ...
    #* Degrees within range [0, 360]. Relative rotation angle of sensor to platform longitudinal axis. Rotation angle between platform longitudinal axis and camera pointing direction as seen from above the platform.
    sensor_relative_azimuth_angle: builtins.float = ...
    #* Degrees within range [-180, 180]. Relative Elevation Angle of sensor to platform longitudinal-transverse plane. Negative angles down.
    sensor_relative_elevation_angle: builtins.float = ...
    #* Degrees within range [0, 360]. Relative roll angle of sensor to aircraft platform. Twisting angle of camera about lens axis. Top of image is zero degrees. Positive angles are clockwise when looking from behind camera.
    sensor_relative_roll_angle: builtins.float = ...
    #* Image sensor provided name/description.
    image_source_sensor: typing.Text = ...
    #* Metadata associated with the specific frame provider, if not a standard MPEG-TS based source
    @property
    def provider_metadata(self) -> global___ProviderMetadata: ...
    def __init__(self,
        *,
        platform_heading_angle : builtins.float = ...,
        platform_pitch_angle : builtins.float = ...,
        platform_roll_angle : builtins.float = ...,
        sensor_latitude : builtins.float = ...,
        sensor_longitude : builtins.float = ...,
        sensor_true_altitude : builtins.float = ...,
        sensor_horizontal_fov : builtins.float = ...,
        sensor_vertical_fov : builtins.float = ...,
        sensor_relative_azimuth_angle : builtins.float = ...,
        sensor_relative_elevation_angle : builtins.float = ...,
        sensor_relative_roll_angle : builtins.float = ...,
        image_source_sensor : typing.Text = ...,
        provider_metadata : typing.Optional[global___ProviderMetadata] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"provider_metadata",b"provider_metadata"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"image_source_sensor",b"image_source_sensor",u"platform_heading_angle",b"platform_heading_angle",u"platform_pitch_angle",b"platform_pitch_angle",u"platform_roll_angle",b"platform_roll_angle",u"provider_metadata",b"provider_metadata",u"sensor_horizontal_fov",b"sensor_horizontal_fov",u"sensor_latitude",b"sensor_latitude",u"sensor_longitude",b"sensor_longitude",u"sensor_relative_azimuth_angle",b"sensor_relative_azimuth_angle",u"sensor_relative_elevation_angle",b"sensor_relative_elevation_angle",u"sensor_relative_roll_angle",b"sensor_relative_roll_angle",u"sensor_true_altitude",b"sensor_true_altitude",u"sensor_vertical_fov",b"sensor_vertical_fov"]) -> None: ...
global___UasMetadata = UasMetadata
